import type { Metadata } from "next";
import "./globals.css";
import FallingParticlesAnimation from "@/components/animations/falling-particles-animation";
import { ScrollProvider } from "@/components/animations/scrollbar/ScrollContext";
import ScrollProgressBar from "@/components/animations/scrollbar/ScrollProgressBar";
import SmoothScrollWrapper from "@/components/animations/scrollbar/SmoothScrollWrapper";
import MountedProvider from "@/providers/mounted-provider";
import { fontAnton, fontRobotoFlex } from "@/config/fonts";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${fontAnton.variable} ${fontRobotoFlex.variable}  antialiased  font-roboto-flex bg-background text-default-100 overflow-hidden`}
      >
        <MountedProvider>
          <FallingParticlesAnimation />
          <ScrollProvider>
            <ScrollProgressBar />
            <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
          </ScrollProvider>
        </MountedProvider>
      </body>
    </html>
  );
}
